name: uupdump canary

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  # push:
  #   branches: [ $default-branch ]
  # pull_request:
  #   branches: [ $default-branch ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: fetch latest build
        id: fetch-latest-build
        run: |
          echo fetching latest build from uupdump.net
          curl "https://api.uupdump.net/fetchupd.php?arch=amd64&ring=canary" >> $RESULT

      - name: print latest build info
        run: |
          echo latest build title: ${{ fromJSON(steps.fetch-latest-build.outputs.result).response.updateTitle }}
          echo latest build id: ${{ fromJSON(steps.fetch-latest-build.outputs.result).response.updateId }}
      
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.